# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epic_image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='epic_image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x65pic_image.proto\"\x07\n\x05\x65mpty\"0\n\nepic_image\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x12\n\nimage_cube\x18\x02 \x01(\x0c\x32k\n\x11\x65pic_post_process\x12&\n\x0f\x66ilter_and_save\x12\x0b.epic_image\x1a\x06.empty\x12.\n\x15\x66ilter_and_save_chunk\x12\x0b.epic_image\x1a\x06.empty(\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_EPIC_IMAGE = _descriptor.Descriptor(
  name='epic_image',
  full_name='epic_image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='epic_image.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_cube', full_name='epic_image.image_cube', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['epic_image'] = _EPIC_IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'epic_image_pb2'
  # @@protoc_insertion_point(class_scope:empty)
  ))
_sym_db.RegisterMessage(empty)

epic_image = _reflection.GeneratedProtocolMessageType('epic_image', (_message.Message,), dict(
  DESCRIPTOR = _EPIC_IMAGE,
  __module__ = 'epic_image_pb2'
  # @@protoc_insertion_point(class_scope:epic_image)
  ))
_sym_db.RegisterMessage(epic_image)



_EPIC_POST_PROCESS = _descriptor.ServiceDescriptor(
  name='epic_post_process',
  full_name='epic_post_process',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='filter_and_save',
    full_name='epic_post_process.filter_and_save',
    index=0,
    containing_service=None,
    input_type=_EPIC_IMAGE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='filter_and_save_chunk',
    full_name='epic_post_process.filter_and_save_chunk',
    index=1,
    containing_service=None,
    input_type=_EPIC_IMAGE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EPIC_POST_PROCESS)

DESCRIPTOR.services_by_name['epic_post_process'] = _EPIC_POST_PROCESS

# @@protoc_insertion_point(module_scope)
