# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epic_image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65pic_image.proto\"\x07\n\x05\x65mpty\"0\n\nepic_image\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x12\n\nimage_cube\x18\x02 \x01(\x0c\x32k\n\x11\x65pic_post_process\x12&\n\x0f\x66ilter_and_save\x12\x0b.epic_image\x1a\x06.empty\x12.\n\x15\x66ilter_and_save_chunk\x12\x0b.epic_image\x1a\x06.empty(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epic_image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _EPIC_IMAGE._serialized_start=29
  _EPIC_IMAGE._serialized_end=77
  _EPIC_POST_PROCESS._serialized_start=79
  _EPIC_POST_PROCESS._serialized_end=186
# @@protoc_insertion_point(module_scope)
